-- Expand default exercise library for existing installations.
-- Existing exercise names are skipped.

CREATE TEMPORARY TABLE tmp_exercise_library_expansion (
    name VARCHAR(160) NOT NULL,
    muscle_group VARCHAR(20) NOT NULL,
    category VARCHAR(80) NOT NULL
) ENGINE=MEMORY DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO tmp_exercise_library_expansion (name, muscle_group, category) VALUES
('Panca piana bilanciere', 'petto', 'forza'),
('Panca inclinata bilanciere', 'petto', 'forza'),
('Panca declinata bilanciere', 'petto', 'forza'),
('Panca piana manubri', 'petto', 'manubri'),
('Panca inclinata manubri', 'petto', 'manubri'),
('Chest press', 'petto', 'macchina'),
('Chest press inclinata', 'petto', 'macchina'),
('Croci manubri', 'petto', 'isolamento'),
('Croci ai cavi', 'petto', 'cavi'),
('Pec deck', 'petto', 'macchina'),
('Dip alle parallele', 'petto', 'corpo libero'),
('Push up', 'petto', 'corpo libero'),
('Pullover manubrio', 'petto', 'isolamento'),
('Lat machine avanti', 'schiena', 'macchina'),
('Lat machine presa stretta', 'schiena', 'macchina'),
('Lat machine inversa', 'schiena', 'macchina'),
('Rematore bilanciere', 'schiena', 'forza'),
('Rematore manubrio', 'schiena', 'manubri'),
('Rematore macchina', 'schiena', 'macchina'),
('Pulley basso', 'schiena', 'macchina'),
('Trazioni alla sbarra', 'schiena', 'corpo libero'),
('Pull up assistito', 'schiena', 'macchina'),
('Pulldown braccia tese', 'schiena', 'cavi'),
('Stacco da terra', 'schiena', 'forza'),
('Hyperextension', 'schiena', 'corpo libero'),
('Face pull', 'schiena', 'cavi'),
('Squat', 'gambe', 'forza'),
('Squat multipower', 'gambe', 'macchina'),
('Hack squat', 'gambe', 'macchina'),
('Leg press', 'gambe', 'macchina'),
('Leg extension', 'gambe', 'macchina'),
('Leg curl sdraiato', 'gambe', 'macchina'),
('Leg curl seduto', 'gambe', 'macchina'),
('Calf machine in piedi', 'gambe', 'macchina'),
('Calf seduto', 'gambe', 'macchina'),
('Hip thrust', 'gambe', 'forza'),
('Glute machine', 'gambe', 'macchina'),
('Abductor machine', 'gambe', 'macchina'),
('Adductor machine', 'gambe', 'macchina'),
('Affondi camminati', 'gambe', 'funzionale'),
('Affondi bulgari', 'gambe', 'corpo libero'),
('Step up', 'gambe', 'funzionale'),
('Romanian deadlift', 'gambe', 'forza'),
('Military press', 'spalle', 'forza'),
('Lento avanti manubri', 'spalle', 'manubri'),
('Alzate laterali', 'spalle', 'isolamento'),
('Alzate laterali ai cavi', 'spalle', 'cavi'),
('Alzate frontali', 'spalle', 'isolamento'),
('Alzate posteriori', 'spalle', 'isolamento'),
('Shoulder press', 'spalle', 'macchina'),
('Shoulder press manubri', 'spalle', 'manubri'),
('Reverse pec deck', 'spalle', 'macchina'),
('Tirate al mento', 'spalle', 'forza'),
('Scrollate manubri', 'spalle', 'isolamento'),
('Curl bilanciere', 'braccia', 'isolamento'),
('Curl manubri alternato', 'braccia', 'manubri'),
('Curl martello', 'braccia', 'manubri'),
('Curl panca Scott', 'braccia', 'macchina'),
('Curl ai cavi', 'braccia', 'cavi'),
('Pushdown cavo', 'braccia', 'isolamento'),
('Pushdown corda', 'braccia', 'cavi'),
('French press', 'braccia', 'isolamento'),
('Estensioni tricipiti sopra testa', 'braccia', 'manubri'),
('Dip tricipiti panca', 'braccia', 'corpo libero'),
('Panca presa stretta', 'braccia', 'forza'),
('Skull crusher', 'braccia', 'isolamento'),
('Plank', 'addome', 'core'),
('Side plank', 'addome', 'core'),
('Crunch', 'addome', 'corpo libero'),
('Crunch inverso', 'addome', 'corpo libero'),
('Crunch machine', 'addome', 'macchina'),
('Leg raise', 'addome', 'core'),
('Hanging leg raise', 'addome', 'corpo libero'),
('Russian twist', 'addome', 'core'),
('Cable crunch', 'addome', 'cavi'),
('Mountain climber', 'addome', 'corpo libero'),
('Ab wheel', 'addome', 'core'),
('Dead bug', 'addome', 'core'),
('Tapis roulant', 'cardio', 'cardio'),
('Camminata in salita', 'cardio', 'cardio'),
('Corsa intervalli', 'cardio', 'cardio'),
('Bike', 'cardio', 'cardio'),
('Bike reclinata', 'cardio', 'cardio'),
('Spin bike', 'cardio', 'cardio'),
('Ellittica', 'cardio', 'cardio'),
('Vogatore', 'cardio', 'cardio'),
('Stepper', 'cardio', 'cardio'),
('SkiErg', 'cardio', 'cardio'),
('Battle rope', 'cardio', 'funzionale'),
('Burpees', 'cardio', 'corpo libero'),
('Jumping jack', 'cardio', 'corpo libero'),
('Salto con corda', 'cardio', 'cardio');

INSERT INTO exercise_library (name, muscle_group, category)
SELECT source.name, source.muscle_group, source.category
FROM tmp_exercise_library_expansion source
WHERE NOT EXISTS (
    SELECT 1
    FROM exercise_library existing
    WHERE existing.name = source.name
);

DROP TEMPORARY TABLE tmp_exercise_library_expansion;
